### ISSUE TITLE
Newest Edison (ACPI-based) support

### ISSUE THREAD

**Issue by andy-shev** [pchizek/edison-ip-pager#1]
I'm wondering if you may use kernel driver for HD44780 and corresponding ACPI table [1] which can be loaded either at boot or at run time (via ConfigFS).

[1]: https://github.com/westeri/meta-acpi/blob/master/recipes-bsp/acpi-tables/samples/edison/hd44780.asl

P.S. It's not an issue with your code nevertheless.

**Comment by pchizek** [comment]
I don't believe so, I'm using a separate Arduino, an Uno, as the controller for the LCD. The breakout board I have for the Edison doesn't have a level shifter, so all of the GPIOs (and digital IO) run at 1.8V. I don't have enough level shifters for all of them which is why I decided to use UART to transmit data to the Uno, which displays it.

**Comment by andy-shev** [comment]
Ah, I see now. Thanks for clarification!
